import os
from pathlib import Path
from typing import List, Optional

class WorkspaceManager:
    def __init__(self, default_workspace: str = "data"):
        # Resolve to handle relative paths like 'data' or './data'
        self.root_path = Path(default_workspace).resolve()
        self._ensure_workspace_exists()

    def set_workspace(self, new_path: str) -> str:
        """Dynamically changes the working directory."""
        target = Path(new_path).resolve()
        if not target.exists():
            target.mkdir(parents=True, exist_ok=True)
        self.root_path = target
        return str(self.root_path)

    def resolve(self, relative_or_absolute_path: str) -> Path:
        """
        Securely maps any path into the active Workspace.
        Prevents Path Traversal (climbing to parent directories) attacks.
        """
        clean_path = str(relative_or_absolute_path).strip()
        
        # Strip common redundant prefixes often generated by LLMs
        for prefix in ["chem-agent/data/", "chem-agent/", "./data/", "data/"]:
            if clean_path.startswith(prefix):
                clean_path = clean_path[len(prefix):]

        # Resolve path
        resolved = (self.root_path / clean_path).resolve()

        # Sandboxing Security Check: Is the resolved path within the Workspace?
        try:
            resolved.relative_to(self.root_path)
        except ValueError:
            raise PermissionError(f"Access Denied: '{relative_or_absolute_path}' is outside the workspace ({self.root_path})!")

        return resolved

    def list_files(self, sub_dir: str = ".") -> List[str]:
        """Lists files under the workspace."""
        try:
            target_dir = self.resolve(sub_dir)
        except (PermissionError, ValueError):
            return []
            
        if not target_dir.is_dir():
            return []
        
        rel_files = []
        for root, _, files in os.walk(target_dir):
            for file in files:
                full_p = Path(root) / file
                try:
                    rel_p = full_p.relative_to(self.root_path)
                    rel_files.append(str(rel_p))
                except ValueError:
                    continue
        return sorted(rel_files)

    def _ensure_workspace_exists(self):
        if not self.root_path.exists():
            self.root_path.mkdir(parents=True, exist_ok=True)
